language: ruby
gemfile:
- gemfiles/rails_4.0.gemfile
- gemfiles/rails_4.1.gemfile
- gemfiles/rails_4.2.gemfile

rvm:
- 2.1.1
before_install:
- pwd
- cd ..
- ln -s ./ruby-habtm-generator ./habtm_generator
- cd habtm_generator
- bundle install --jobs=3 --retry=3
script:
- bundle exec rake test
